FROM node:20.11.0
WORKDIR /app

COPY package*.json ./

#copy all the files and folders from my project to app directory
COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm","run","start"]